### ISSUE TITLE
Unable to generate npc dnd 3.3.1 v12 foundry

### ISSUE THREAD

**Issue by Aura-6931** [elizeuangelo/fvtt-module-npc-generator-dnd5e-faq#3]
Howdy all, I'm on v1.5.5, not sure what to do.

Foundry VTT | Rendering FilePicker
utils.js:18 NPC Generator | Fetched ./tables/bonds/base.csv
utils.js:18 NPC Generator | Fetched ./tables/ideals/base.csv
utils.js:18 NPC Generator | Fetched ./tables/personality/base.csv
utils.js:18 NPC Generator | Fetched ./tables/flaw/base.csv
utils.js:18 NPC Generator | Fetched ./tables/plot/base.csv
foundry.js:72076 Building a NPC, please wait...
foundry.js:72076 Something weird happened and NPC failed to build.
fetch @ foundry.js:72076
item5e.js:13 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[No packages detected]
    at Function.values (<anonymous>)
    at getActivity (item5e.js:13:19)
    at getActionType (item5e.js:21:17)
    at NPCDraft.updateWeaponDescription (npcdraft.js:1105:305)
    at NPCDraft.weapon (npcdraft.js:1080:18)
    at async Object.apply (evoker.js:36:9)
    at async NPCDraft.applyJob (npcdraft.js:524:9)
    at async NPCDraft.prepare (npcdraft.js:389:9)
    at async NPCDraft.create (npcdraft.js:73:25)
foundry.js:72076 Building a NPC, please wait...
foundry.js:72076 Something weird happened and NPC failed to build.
fetch @ foundry.js:72076
notify @ foundry.js:71972
🎁call_wrapped @ libWrapper-wrapper.js:511
notificationNotify @ utils.js:4668
🎁call_wrapper @ libWrapper-wrapper.js:639
🎁Notifications.prototype.notify#0 @ libWrapper-wrapper.js:193
🎁call_wrapped @ libWrapper-wrapper.js:511
_lw_ui_notifications_notify @ Bundle.js:132797
🎁call_wrapper @ libWrapper-wrapper.js:639
🎁ui.notifications.notify#0 @ libWrapper-wrapper.js:193
error @ foundry.js:72009
create @ npcdraft.js:87
item5e.js:13 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[No packages detected]
    at Function.values (<anonymous>)
    at getActivity (item5e.js:13:19)
    at getActionType (item5e.js:21:17)
    at NPCDraft.updateWeaponDescription (npcdraft.js:1105:305)
    at NPCDraft.weapon (npcdraft.js:1080:18)
    at async Object.apply (evoker.js:36:9)
    at async NPCDraft.applyJob (npcdraft.js:524:9)
    at async NPCDraft.prepare (npcdraft.js:389:9)
    at async NPCDraft.create (npcdraft.js:73:25)
getActivity @ item5e.js:13
getActionType @ item5e.js:21
updateWeaponDescription @ npcdraft.js:1105
weapon @ npcdraft.js:1080

**Comment by tphockenberry** [comment]
Same here. Hope it gets fixed especially since it was a paid module.

**Comment by elizeuangelo** [comment]
I'm taking a look this weekend

**Comment by elizeuangelo** [comment]
Version v1.26.1 released. There is still a remaining bug on the warlock but I will be fixing it soon.

**Comment by elizeuangelo** [comment]
@Aura-6931 I forgot to ask, you are in which version of foundry and DnD? v1.5.5 seems a rather old version of the module.

**Comment by tphockenberry** [comment]
I was using module version 1.25.1 on foundry v12-331. I just upgraded to 1.26.1 and have the same issue.

**Comment by tphockenberry** [comment]
![image](https://github.com/user-attachments/assets/d8527831-e35a-4e65-82e7-3c7db7df32ff)

**Comment by Aura6931** [comment]
Foundry v 12 (not 13)

**Comment by elizeuangelo** [comment]
@Aura-6931 which dnd version? If you can please talk to me in discord @mad.wizard

**Comment by tphockenberry** [comment]
5E 3.3.1 here

**Comment by Aura-6931** [comment]
5e 3.3.1 as well.

**Comment by elizeuangelo** [comment]
I see! Module v1.25.1 onwards doesnt work on DnD 5e v3. It was the first version made for DnD v4.
Contact me in Discord: `mad.wizard` and I will get you a working version for DnD 5e v3 (module v1.24.2).

**Comment by Aura-6931** [comment]
I can confirm that 1.24.2 works on 3.3.1!

**Comment by tphockenberry** [comment]
Understood. I will be rolling back to 1.24.2 as well. Just a point for quality improvement - your change log for 1.25.1 says:
Adds support for DnD v4.1.1
That needs to be much clearer that it ONLY supports 5E version 4 going forward. The word "added" suggests they both exist together. It might be nit-picking but I have been paying particiuar attention to change logs when upgrading modules and sorry but it just wasn't warning enough. Thanks for the attention to the issue and your work!

**Comment by elizeuangelo** [comment]
> Understood. I will be rolling back to 1.24.2 as well. Just a point for quality improvement - your change log for 1.25.1 says: Adds support for DnD v4.1.1 That needs to be much clearer that it ONLY supports 5E version 4 going forward. The word "added" suggests they both exist together. It might be nit-picking but I have been paying particiuar attention to change logs when upgrading modules and sorry but it just wasn't warning enough. Thanks for the attention to the issue and your work!

You are absolutely right, I should've made it clearer.
Thank you all for the feedback and sorry for all the issues involved.

**Comment by Aura-6931** [comment]
Thank you for your module as it's helped so much!

**Comment by Aura-6931** [comment]
So I tried using NPC generator on 1.24.2 but It gave me an error. Hm... What's up?

Foundry VTT | Rendering FilePicker
foundry.js:7845 Foundry VTT | Retrieved and compiled template templates/apps/filepicker.html
foundry.js:72076 Building a NPC, please wait...
foundry-esm.js:4621 Error: You are accessing globalThis.mergeObject which must now be accessed via foundry.utils.mergeObject
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at get (foundry-esm.js:66671:25)
    at new NPCDraft (npcdraft.js:366:9)
    at NPCDraft.create (npcdraft.js:73:31)
    at HTMLButtonElement.<anonymous> (menu.js:645:22)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
logCompatibilityWarning @ foundry-esm.js:4621
foundry-esm.js:4621 Error: You are accessing globalThis.mergeObject which must now be accessed via foundry.utils.mergeObject
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at get (foundry-esm.js:66671:25)
    at NPCDraft.evaluateSpellDmg (npcdraft.js:961:9)
    at npcdraft.js:1234:59
    at Array.map (<anonymous>)
    at NPCDraft.setOffensePower (npcdraft.js:1234:39)
    at NPCDraft.prepare (npcdraft.js:399:14)
    at async NPCDraft.create (npcdraft.js:73:25)
logCompatibilityWarning @ foundry-esm.js:4621
foundry.js:72076 Something weird happened and NPC failed to build.
fetch @ foundry.js:72076
npcdraft.js:1445 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sourceId')
[No packages detected]
    at NPCDraft.updateItemsDescription (npcdraft.js:1445:120)
    at NPCDraft.prepare (npcdraft.js:401:14)
    at async NPCDraft.create (npcdraft.js:73:25)
54Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.

**Comment by tphockenberry** [comment]
Not working for me anymore either. This issue was closed so I'm not sure your comment will be seen.

**Comment by Aura-6931** [comment]
thanks I'll make a new issue then

**Comment by elizeuangelo** [comment]
Which version of Foundry and DnD are you using?

**Comment by Aura-6931** [comment]
Version 12.331 of foundry and dnd 3.3.1

**Comment by Aura-6931** [comment]
I just don't understand what's up. I'd upgrade to 4.0 dnd but I would lose out on so many of my addons.

**Comment by elizeuangelo** [comment]
I think v1.24.2 was only compatible up to Foundry v11... I can make a release on demand for you guys for foundry v12 for DnD v3 but please answer me first if you are using Forge or hosting yourselves.

If using Forge I THINK I can make it available for everyone (under v1.24.3) but otherwise I would need to provide a link specially for you to use.

**Comment by tphockenberry** [comment]
I use forge. Any release on github we can use with just a link to the manifest. It was working before on v12 after falling back to 1.24.2. not sure what happened since.

**Comment by elizeuangelo** [comment]
Sorry about all the delay, I'm having lots of work but i finally found the time to address this. It turned out it was an much easier fix than I antecipated, I just release v1.24.3 which should solve DnD3e issues with Foundry v12. Let me know if you have any trouble downloading it or using that version.
